import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const customFont = localFont({src: '../../font/Century-Condensed-Regular.ttf'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={customFont.className}>{children}</body>
    </html>
  )
}
