import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Header from './_components/layouts/Header'
import MenuNavigate from './_components/layouts/MenuNavigate'

const customFont = localFont({ src: '../../font/Century-Condensed-Regular.ttf' })

export const metadata: Metadata = {
  title: 'Pizza 4Ps',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={customFont.className}>
        <Header />
        <MenuNavigate />
        {children}</body>
    </html>
  )
}
